target-version = "py38"
line-length = 88
exclude = [
  ".direnv",
  ".git",
  ".github",
  ".ipynb_checkpoints",
  ".pytest_cache",
  ".venv",
  "__pycache__",
  "docker",
  "htmlcov",
  "venv",
]
extend-select = [
  "A",  # flake8-builtins
  "I",  # isort
  "INP",  # flake8-no-pep420
  "ISC",  # flake8-implicit-str-concat
  "UP",  # pyupgrade
  "W",  # pycodestyle warning
]
extend-ignore = [
  "E501",
  "E731",
  "A001", # problem existed in code before using Ruff; consider fixing in future
  "A002", # problem existed in code before using Ruff; consider fixing in future
  "A003", # problem existed in code before using Ruff; consider fixing in future
]

[extend-per-file-ignores]
"tests/fixtures/studies/test_params/analysis/study_definition.py" = ["INP001"]
"tests/fixtures/studies/test_patients_from_file/analysis/study_definition_controls.py" = ["INP001"]
"tests/fixtures/studies/test_smoketest/analysis/study_definition.py" = ["INP001"]
"tests/fixtures/studies/test_suppresses_small_numbers/analysis/study_definition.py" = ["INP001"]

[isort]
lines-after-imports = 2
