CREATE DATABASE Test_OpenCorona;
ALTER DATABASE Test_OpenCorona SET COMPATIBILITY_LEVEL = 100;
CREATE DATABASE OPENCoronaTempTables;
ALTER DATABASE OPENCoronaTempTables SET COMPATIBILITY_LEVEL = 100;
CREATE DATABASE Test_EMIS;

GO
